INSERT INTO translations (locale, key, text) VALUES
    ('es-CO', 'add.estimate-result', 'Estimada: hasta el {date} (unos {days} días donde lo guardas)'),
    ('en', 'add.estimate-result', 'Estimated: until {date} (about {days} days where you keep it)'),
    ('es-CO', 'add.expiry.estimate', 'No sé: estímala'),
    ('en', 'add.expiry.estimate', 'I don''t know: estimate it'),
    ('es-CO', 'add.expiry.known', 'Sé la fecha'),
    ('en', 'add.expiry.known', 'I know the date'),
    ('es-CO', 'add.expiry.photo', 'Foto de la etiqueta'),
    ('en', 'add.expiry.photo', 'Photo of the label'),
    ('es-CO', 'add.missing', 'Elige un alimento, los gramos y dónde va'),
    ('en', 'add.missing', 'Choose a food, the grams, and where it goes'),
    ('es-CO', 'add.opened', 'Ya está abierto'),
    ('en', 'add.opened', 'It is already opened'),
    ('es-CO', 'add.photo', 'Toma o elige una foto de la etiqueta'),
    ('en', 'add.photo', 'Take or choose a photo of the label'),
    ('es-CO', 'add.photo-needs-food', 'Primero elige el alimento y dónde va'),
    ('en', 'add.photo-needs-food', 'Choose the food and where it goes first'),
    ('es-CO', 'add.photo-reading', 'Leyendo la etiqueta…'),
    ('en', 'add.photo-reading', 'Reading the label…'),
    ('es-CO', 'add.photo-result', 'Hasta el {date}. {reason}'),
    ('en', 'add.photo-result', 'Until {date}. {reason}'),
    ('es-CO', 'add.search', 'Busca el alimento, por ejemplo pollo o leche'),
    ('en', 'add.search', 'Search food, for example pollo or milk'),
    ('es-CO', 'add.step.amount', '¿Cuánto?'),
    ('en', 'add.step.amount', 'How much?'),
    ('es-CO', 'add.step.expiry', '¿Cuándo vence?'),
    ('en', 'add.step.expiry', 'When does it expire?'),
    ('es-CO', 'add.step.food', '¿Qué vas a guardar?'),
    ('en', 'add.step.food', 'What are you putting in?'),
    ('es-CO', 'add.step.where', '¿Dónde lo guardas?'),
    ('en', 'add.step.where', 'Where does it go?'),
    ('es-CO', 'expiry.estimated', 'estimada'),
    ('en', 'expiry.estimated', 'estimated'),
    ('es-CO', 'expiry.label', 'de la etiqueta'),
    ('en', 'expiry.label', 'from the label'),
    ('es-CO', 'fridge.opened', 'Lo abrí'),
    ('en', 'fridge.opened', 'Opened'),
    ('es-CO', 'fridge.toast-opened', 'Abriste {food}. Fecha límite: {date}'),
    ('en', 'fridge.toast-opened', '{food} is open; use it by {date}')
ON CONFLICT (locale, key) DO UPDATE SET text = EXCLUDED.text, updated_at = now();
