INSERT INTO translations (locale, key, text) VALUES
    ('es-CO', 'allergen.CELERY', 'Apio'),
    ('en', 'allergen.CELERY', 'Celery'),
    ('es-CO', 'allergen.CRUSTACEANS', 'Crustáceos'),
    ('en', 'allergen.CRUSTACEANS', 'Crustaceans'),
    ('es-CO', 'allergen.EGGS', 'Huevo'),
    ('en', 'allergen.EGGS', 'Eggs'),
    ('es-CO', 'allergen.FISH', 'Pescado'),
    ('en', 'allergen.FISH', 'Fish'),
    ('es-CO', 'allergen.GLUTEN', 'Gluten'),
    ('en', 'allergen.GLUTEN', 'Gluten'),
    ('es-CO', 'allergen.LUPIN', 'Altramuz'),
    ('en', 'allergen.LUPIN', 'Lupin'),
    ('es-CO', 'allergen.MILK', 'Leche'),
    ('en', 'allergen.MILK', 'Milk'),
    ('es-CO', 'allergen.MOLLUSCS', 'Moluscos'),
    ('en', 'allergen.MOLLUSCS', 'Molluscs'),
    ('es-CO', 'allergen.MUSTARD', 'Mostaza'),
    ('en', 'allergen.MUSTARD', 'Mustard'),
    ('es-CO', 'allergen.PEANUTS', 'Maní'),
    ('en', 'allergen.PEANUTS', 'Peanuts'),
    ('es-CO', 'allergen.SESAME', 'Ajonjolí'),
    ('en', 'allergen.SESAME', 'Sesame'),
    ('es-CO', 'allergen.SOY', 'Soya'),
    ('en', 'allergen.SOY', 'Soy'),
    ('es-CO', 'allergen.SULPHITES', 'Sulfitos'),
    ('en', 'allergen.SULPHITES', 'Sulphites'),
    ('es-CO', 'allergen.TREE_NUTS', 'Nueces'),
    ('en', 'allergen.TREE_NUTS', 'Tree nuts'),
    ('es-CO', 'channel.LOG', 'Registro del servidor'),
    ('en', 'channel.LOG', 'Server log'),
    ('es-CO', 'channel.TELEGRAM', 'Telegram'),
    ('en', 'channel.TELEGRAM', 'Telegram'),
    ('es-CO', 'channel.WEB', 'En la app'),
    ('en', 'channel.WEB', 'In the app'),
    ('es-CO', 'diet.OMNIVORE', 'Come de todo'),
    ('en', 'diet.OMNIVORE', 'Eats everything'),
    ('es-CO', 'diet.PESCATARIAN', 'Pescetariano'),
    ('en', 'diet.PESCATARIAN', 'Pescatarian'),
    ('es-CO', 'diet.VEGAN', 'Vegano'),
    ('en', 'diet.VEGAN', 'Vegan'),
    ('es-CO', 'diet.VEGETARIAN', 'Vegetariano'),
    ('en', 'diet.VEGETARIAN', 'Vegetarian'),
    ('es-CO', 'nav.settings', 'Ajustes'),
    ('en', 'nav.settings', 'Settings'),
    ('es-CO', 'now.missing-food', '{food} (falta)'),
    ('en', 'now.missing-food', '{food} (missing)'),
    ('es-CO', 'now.servings.one', '{n} persona'),
    ('en', 'now.servings.one', '{n} person'),
    ('es-CO', 'now.servings.other', '{n} personas'),
    ('en', 'now.servings.other', '{n} people'),
    ('es-CO', 'settings.alerts', 'Alertas'),
    ('en', 'settings.alerts', 'Alerts'),
    ('es-CO', 'settings.alerts-hint', 'Puerta abierta, nevera caliente y resúmenes te llegan por aquí.'),
    ('en', 'settings.alerts-hint', 'Door left open, a warm fridge, and briefings reach you here.'),
    ('es-CO', 'settings.allergies', 'Alergias'),
    ('en', 'settings.allergies', 'Allergies'),
    ('es-CO', 'settings.avoided', 'Alimentos que evitas, separados por comas'),
    ('en', 'settings.avoided', 'Foods you avoid, separated by commas'),
    ('es-CO', 'settings.avoided-example', 'cilantro, hígado'),
    ('en', 'settings.avoided-example', 'cilantro, liver'),
    ('es-CO', 'settings.changed', 'Cambiado'),
    ('en', 'settings.changed', 'Changed'),
    ('es-CO', 'settings.default', 'Por defecto: {value}'),
    ('en', 'settings.default', 'Default: {value}'),
    ('es-CO', 'settings.diet', 'Dieta'),
    ('en', 'settings.diet', 'Diet'),
    ('es-CO', 'settings.household', 'Cómo está ajustado tu hogar'),
    ('en', 'settings.household', 'How your home is tuned'),
    ('es-CO', 'settings.household-hint', 'Cada valor tiene un rango seguro; puedes volver al valor por defecto cuando quieras.'),
    ('en', 'settings.household-hint', 'Each value has a safe range; restore the default at any time.'),
    ('es-CO', 'settings.household-readonly', 'Solo el dueño del hogar puede cambiar estos valores.'),
    ('en', 'settings.household-readonly', 'Only the owner of the home can change these values.'),
    ('es-CO', 'settings.language', 'Idioma'),
    ('en', 'settings.language', 'Language'),
    ('es-CO', 'settings.language-hint', 'Las pantallas, los mensajes y la voz del Chef siguen esta elección en todos tus dispositivos.'),
    ('en', 'settings.language-hint', 'Screens, messages, and the Chef voice follow this choice on every device.'),
    ('es-CO', 'settings.lead', 'Tu idioma, lo que puedes comer, cómo te llegan las alertas y cómo está ajustado tu hogar.'),
    ('en', 'settings.lead', 'Your language, what you can eat, how alerts reach you, and how your home is tuned.'),
    ('es-CO', 'settings.profile', 'Lo que comes'),
    ('en', 'settings.profile', 'What you eat'),
    ('es-CO', 'settings.profile-hint', 'Cocinar ya, los sustitutos y el plan respetan tu dieta y tus alergias.'),
    ('en', 'settings.profile-hint', 'Cook now, substitutions, and the plan respect your diet and allergies.'),
    ('es-CO', 'settings.reset', 'Usar el valor por defecto'),
    ('en', 'settings.reset', 'Use the default'),
    ('es-CO', 'settings.save', 'Guardar'),
    ('en', 'settings.save', 'Save'),
    ('es-CO', 'settings.save-alerts', 'Guardar alertas'),
    ('en', 'settings.save-alerts', 'Save alerts'),
    ('es-CO', 'settings.save-profile', 'Guardar lo que como'),
    ('en', 'settings.save-profile', 'Save what I eat'),
    ('es-CO', 'settings.telegram', 'Id del chat de Telegram'),
    ('en', 'settings.telegram', 'Telegram chat id'),
    ('es-CO', 'settings.title', 'Ajustes'),
    ('en', 'settings.title', 'Settings'),
    ('es-CO', 'settings.toast-alerts', 'Guardaste tus alertas'),
    ('en', 'settings.toast-alerts', 'Saved your alerts'),
    ('es-CO', 'settings.toast-language', 'Idioma cambiado'),
    ('en', 'settings.toast-language', 'Language changed'),
    ('es-CO', 'settings.toast-profile', 'Guardaste lo que comes'),
    ('en', 'settings.toast-profile', 'Saved what you eat'),
    ('es-CO', 'settings.toast-reset', 'De vuelta al valor por defecto'),
    ('en', 'settings.toast-reset', 'Back to the default'),
    ('es-CO', 'settings.toast-saved', 'Guardaste el ajuste'),
    ('en', 'settings.toast-saved', 'Saved the setting'),
    ('es-CO', 'settings.unit.days', 'días'),
    ('en', 'settings.unit.days', 'days'),
    ('es-CO', 'settings.value', 'Valor'),
    ('en', 'settings.value', 'Value')
ON CONFLICT (locale, key) DO UPDATE SET text = EXCLUDED.text, updated_at = now();
